{% set name = "perl-net-ssleay" %}
{% set version = "1.94" %}
{% set sha256 = "9d7be8a56d1bedda05c425306cc504ba134307e0c09bda4a788c98744ebcd95d" %}

package:
  name: perl-net-ssleay
  version: {{ version }}

source:
   url: https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-mime-base64
    - openssl
    - zlib

  run:
    - perl
    - perl-mime-base64
    - openssl
    - zlib

test:
  imports:
    - Net::SSLeay

about:
  home: https://metacpan.org/dist/Net-SSLeay
  license: Artistic-2.0
  summary: 'Perl extension for using OpenSSL'
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cbrueffer
